### ISSUE TITLE
ReferenceError: target is not defined

### ISSUE THREAD

**Issue by johncaruso** [bryceg/servicenow-skeleton-typescript#7]
Bryce, nice to see your still improving this project. I thought I'd (finally) try it out, but unfortunately got the following error on the second step of **Node Project Setup**:

```
C:\Users\johnc\Desktop\repos\t1>node_modules\.bin\skeleton init
Initializing ServiceNow Skeleton Project
C:\Users\johnc\Desktop\repos\t1\node_modules\servicenow-dev-skeleton\bin\skeleton.js:21
        var dest = path.join(appRoot, path.basename(target));
                                                    ^

ReferenceError: target is not defined
    at copyFiles.forEach.file (C:\Users\johnc\Desktop\repos\t1\node_modules\servicenow-dev-skeleton\bin\skeleton.js:21:53)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\johnc\Desktop\repos\t1\node_modules\servicenow-dev-skeleton\bin\skeleton.js:20:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

**Comment by bryceg** [comment]
Thanks John, I'll try to take a look at this soon and fix it.  Have not set up a new project yet with the updated framework, obviously did not test that well :)  Think I'm missing a few other components now that I'm thinking about it, thanks.

**Comment by ajbenton** [comment]
I think this issue was fixed a couple of weeks ago in this commit:
[2.1.1](https://github.com/bryceg/servicenow-skeleton-typescript/commit/94118451589bcd4315bb7b5380d34430c7ff89fd)
